### ISSUE TITLE
Week 1/2 Ready for review

### ISSUE THREAD

**Issue by ian-deloach** [ian-deloach/BiteSize#1]
@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @ian-deloach - In the interest of time reviewing late work, I'm going to limit my feedback to areas for improvement related to Checkpoint 1 and Checkpoint 2. 

- [ ] Project plan lacks detail to demonstrate what you will do and when. One approach is to document when you will complete each user story, and then break each user story down into smaller tasks. Also consider the deliverables of the project itself - some of those will make good tasks such as deploying to AWS, final project video presentation, peer review, fixes from peer review comments, checkpoint 3 tasks, etc. 
- [x] One of the requirements of the project is to demonstrate full CRUD. I don't think there is a story representing the delete scenarios. Is there something meaningful that you can add to meet this requirement?
- [x] ERD/Screens - should theme be a separate table to make the dropdown/avoiding duplicates easier? 
- [ ] Journal/timelog should track all time spend on ENT java. It might be helpful to imagine that Ent Java is a job and you want to make sure you get paid for all your work :) 
- [ ] What web service/api are you planning to incorporate? This should be documented in the project plan and as a tech on the readme.md.
- [x] There are some sneaky printStackTrace statements that should be logged instead. You may need to throw the exception to the caller for logging since this in the interface.  https://github.com/ian-deloach/BiteSize/blob/7d96cf381c4ed5f570d08c948c48109fb659c3d9/src/main/java/biteSize/utilities/PropertiesLoader.java#L24-L28
